import React, { useRef } from "react";
import { Bar } from "react-chartjs-2";
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend,
} from "chart.js";
import { Package, DollarSign, Download, FileText } from "lucide-react";
import jsPDF from "jspdf";
import "jspdf-autotable";

ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip,
  Legend
);

const ProductReport = ({ products = {}, startDate, endDate }) => {
  const chartRef = useRef(null);

  // Default to empty object if products is undefined
  const {
    totalListings = 0,
    activeListings = 0,
    avgPrice = 0,
    topCategories = [],
    productPerformance = [],
  } = products;

  // Chart data for Product Statistics
  const chartData = {
    labels: ["Total Listings", "Active Listings"],
    datasets: [
      {
        label: "Products",
        data: [totalListings, activeListings],
        backgroundColor: [
          "rgba(75, 192, 192, 0.6)",
          "rgba(153, 102, 255, 0.6)",
        ],
        borderColor: ["rgba(75, 192, 192, 1)", "rgba(153, 102, 255, 1)"],
        borderWidth: 1,
      },
    ],
  };

  const chartOptions = {
    responsive: true,
    plugins: {
      legend: { position: "top" },
      title: {
        display: true,
        text: "Product Statistics",
      },
    },
    scales: { y: { beginAtZero: true } },
  };

  // Function to download PDF
  const downloadPDF = () => {
    if (
      !totalListings &&
      !activeListings &&
      !avgPrice &&
      topCategories.length === 0 &&
      productPerformance.length === 0
    ) {
      alert("Cannot export report. No data available.");
      return;
    }

    const reportTitle = "AGRILINK ETHIOPIA";
    const reportType = "Product Analytics Report";
    const period = `${startDate} to ${endDate}`; // Use passed startDate and endDate
    const filePeriod = `${new Date().toISOString().split("T")[0]}`;
    const pageHeight = 297; // A4 height in mm
    const bottomMargin = 20;
    const maxY = pageHeight - bottomMargin;

    const doc = new jsPDF();
    let y = 20;

    // Helper function to add new page if content overflows
    const checkPageOverflow = () => {
      if (y > maxY) {
        doc.addPage();
        y = 20;
        addHeaderFooter();
      }
    };

    // Helper function to add header and footer
    const addHeaderFooter = () => {
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.setFont("helvetica", "normal");
      doc.text(
        `Page ${doc.internal.getNumberOfPages()}`,
        doc.internal.pageSize.width - 30,
        pageHeight - 10,
        { align: "right" }
      );
      doc.text("Generated by AgriLink Ethiopia", 20, pageHeight - 10);
    };

    // Initial header and footer
    addHeaderFooter();

    // Title: AGRILINK ETHIOPIA
    doc.setFontSize(28);
    doc.setTextColor(0, 128, 0); // Green
    doc.setFont("helvetica", "bold");
    doc.text(reportTitle, doc.internal.pageSize.width / 2, y, {
      align: "center",
    });
    y += 15;

    // Report Type
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text(reportType, doc.internal.pageSize.width / 2, y, {
      align: "center",
    });
    y += 10;

    // Period
    doc.setFontSize(14);
    doc.setFont("helvetica", "italic");
    doc.text(`Period: ${period}`, doc.internal.pageSize.width / 2, y, {
      align: "center",
    });
    y += 15;

    doc.setFontSize(14);
    doc.setFont("helvetica", "italic");
    doc.text(
      `Report Generated on Date: ${filePeriod}`,
      doc.internal.pageSize.width / 2,
      y,
      {
        align: "center",
      }
    );
    y += 15;

    // Divider
    doc.setLineWidth(0.5);
    doc.setDrawColor(0, 128, 0);
    doc.line(20, y, doc.internal.pageSize.width - 20, y);
    y += 10;

    // Product Statistics Section
    doc.setFontSize(16);
    doc.setTextColor(0, 128, 0);
    doc.setFont("helvetica", "bold");
    doc.text("Product Statistics Overview", 20, y);
    y += 8;

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.text(
      "Key metrics showcasing product listings and performance on AgriLink Ethiopia",
      20,
      y
    );
    y += 8;
    checkPageOverflow();

    doc.text(
      `Total Listings: ${totalListings.toLocaleString()} (All product listings)`,
      20,
      y
    );
    y += 8;
    checkPageOverflow();
    doc.text(
      `Active Listings: ${activeListings.toLocaleString()} (Currently available products)`,
      20,
      y
    );
    y += 8;
    checkPageOverflow();
    doc.text(
      `Average Price: ETB ${avgPrice.toLocaleString()} (Per product listing)`,
      20,
      y
    );
    y += 8;
    checkPageOverflow();

    // Add the bar chart
    if (chartRef.current) {
      const chartImage = chartRef.current.toBase64Image();
      doc.addImage(chartImage, "PNG", 20, y, 170, 85);
      y += 90;
      checkPageOverflow();
    } else {
      doc.text("Product statistics chart not available in this export.", 20, y);
      y += 10;
      checkPageOverflow();
    }

    // Divider
    doc.setLineWidth(0.5);
    doc.setDrawColor(0, 128, 0);
    doc.line(20, y, doc.internal.pageSize.width - 20, y);
    y += 10;
    checkPageOverflow();

    // Top Categories Section
    doc.setFontSize(16);
    doc.setTextColor(0, 128, 0);
    doc.setFont("helvetica", "bold");
    doc.text("Top Categories by Performance", 20, y);
    y += 8;
    checkPageOverflow();

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.text("Performance metrics by product category", 20, y);
    y += 8;
    checkPageOverflow();

    // Table header for Top Categories
    doc.setFont("helvetica", "bold");
    doc.text("Category", 20, y);
    doc.text("Listings", 90, y, { align: "right" });
    doc.text("Orders", 130, y, { align: "right" });
    doc.text("Revenue", 190, y, { align: "right" });
    y += 6;
    doc.setLineWidth(0.2);
    doc.line(20, y, 190, y);
    y += 4;
    checkPageOverflow();

    // Table rows for Top Categories
    doc.setFont("helvetica", "normal");
    topCategories.forEach((category) => {
      doc.text(category.category || "N/A", 20, y);
      doc.text((category.listings || 0).toLocaleString(), 90, y, {
        align: "right",
      });
      doc.text((category.orders || 0).toLocaleString(), 130, y, {
        align: "right",
      });
      doc.text(`ETB ${(category.revenue || 0).toLocaleString()}`, 190, y, {
        align: "right",
      });
      y += 8;
      checkPageOverflow();
    });

    // Divider
    doc.setLineWidth(0.5);
    doc.setDrawColor(0, 128, 0);
    doc.line(20, y, doc.internal.pageSize.width - 20, y);
    y += 10;
    checkPageOverflow();

    // Product Performance Section
    doc.setFontSize(16);
    doc.setTextColor(0, 128, 0);
    doc.setFont("helvetica", "bold");
    doc.text("Product Performance", 20, y);
    y += 8;
    checkPageOverflow();

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.text("Top products by sales percentage", 20, y);
    y += 8;
    checkPageOverflow();

    // Table header for Product Performance
    doc.setFont("helvetica", "bold");
    doc.text("Product", 20, y);
    doc.text("Orders", 90, y, { align: "right" });
    doc.text("Sales %", 130, y, { align: "right" });
    y += 6;
    doc.setLineWidth(0.2);
    doc.line(20, y, 190, y);
    y += 4;
    checkPageOverflow();

    // Table rows for Product Performance
    doc.setFont("helvetica", "normal");
    productPerformance.forEach((product) => {
      doc.text(product.product || "N/A", 20, y);
      doc.text((product.orders || 0).toLocaleString(), 90, y, {
        align: "right",
      });
      doc.text(`${Number(product.salesPercentage || 0).toFixed(1)}%`, 130, y, {
        align: "right",
      });
      y += 8;
      checkPageOverflow();
    });

    doc.save(`product_analytics_report_${filePeriod}.pdf`);
  };

  // Function to download CSV
  const downloadCSV = () => {
    if (
      !totalListings &&
      !activeListings &&
      !avgPrice &&
      topCategories.length === 0 &&
      productPerformance.length === 0
    ) {
      alert("Cannot export report. No data available.");
      return;
    }

    let csvContent = "data:text/csv;charset=utf-8,";
    csvContent += "Metric,Value\n";
    csvContent += `Total Listings,${totalListings}\n`;
    csvContent += `Active Listings,${activeListings}\n`;
    csvContent += `Average Price,${avgPrice}\n`;
    if (topCategories.length > 0) {
      csvContent += "\nCategory,Listings,Orders,Revenue\n";
      topCategories.forEach((category) => {
        csvContent += `${category.category || "N/A"},${
          category.listings || 0
        },${category.orders || 0},${category.revenue || 0}\n`;
      });
    }
    if (productPerformance.length > 0) {
      csvContent += "\nProduct,Orders,Sales Percentage\n";
      productPerformance.forEach((product) => {
        csvContent += `${product.product || "N/A"},${
          product.orders || 0
        },${Number(product.salesPercentage || 0).toFixed(1)}%\n`;
      });
    }

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute(
      "download",
      `product_analytics_report_${new Date().toISOString().split("T")[0]}.csv`
    );
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="mb-4">
      <div className="d-flex justify-content-end gap-2 mb-4">
        <button
          className="btn btn-primary btn-sm"
          onClick={downloadPDF}
          style={{ fontSize: "14px", padding: "6px 12px" }}
        >
          <Download size={16} className="me-2" />
          Export PDF
        </button>
        <button
          className="btn btn-primary btn-sm"
          onClick={downloadCSV}
          style={{ fontSize: "14px", padding: "6px 12px" }}
        >
          <FileText size={16} className="me-2" />
          Export CSV
        </button>
      </div>

      <div className="row row-cols-1 row-cols-md-2 row-cols-lg-4 g-4 mb-4">
        <div className="col">
          <div className="card summary-card h-100">
            <div className="summary-card-header">
              <h6 className="summary-card-title">Total Listings</h6>
              <Package size={24} className="summary-card-icon" />
            </div>
            <div className="summary-card-body">
              <h3 className="summary-card-value">
                {totalListings.toLocaleString()}
              </h3>
              <p className="summary-card-subtext text-muted">
                All product listings
              </p>
            </div>
          </div>
        </div>
        <div className="col">
          <div className="card summary-card h-100">
            <div className="summary-card-header">
              <h6 className="summary-card-title">Active Listings</h6>
              <Package size={24} className="summary-card-icon" />
            </div>
            <div className="summary-card-body">
              <h3 className="summary-card-value">
                {activeListings.toLocaleString()}
              </h3>
              <p className="summary-card-subtext text-muted">
                {(activeListings / totalListings || 0 * 100).toFixed(1)}% of
                total
              </p>
            </div>
          </div>
        </div>
        <div className="col">
          <div className="card summary-card h-100">
            <div className="summary-card-header">
              <h6 className="summary-card-title">Average Price</h6>
              <DollarSign size={24} className="summary-card-icon" />
            </div>
            <div className="summary-card-body">
              <h3 className="summary-card-value">
                ETB {avgPrice.toLocaleString()}
              </h3>
              <p className="summary-card-subtext text-muted">
                Per product listing
              </p>
            </div>
          </div>
        </div>
        <div className="col">
          <div className="card summary-card h-100">
            <div className="summary-card-header">
              <h6 className="summary-card-title">Categories</h6>
              <Package size={24} className="summary-card-icon" />
            </div>
            <div className="summary-card-body">
              <h3 className="summary-card-value">{topCategories.length}</h3>
              <p className="summary-card-subtext text-muted">
                Product categories
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="card mb-4">
        <div className="card-header">
          <h5 className="card-title">Product Statistics</h5>
          <p className="card-text text-muted">
            Overview of product listings and activity
          </p>
        </div>
        <div className="card-body">
          <Bar ref={chartRef} data={chartData} options={chartOptions} />
        </div>
      </div>

      <div className="row row-cols-1 row-cols-lg-2 g-4">
        <div className="col">
          <div className="card">
            <div className="card-header">
              <h5 className="card-title">Top Categories</h5>
              <p className="card-text text-muted">
                Performance by product category
              </p>
            </div>
            <div className="card-body">
              <div className="table-responsive">
                <table className="table table-striped">
                  <thead>
                    <tr style={{ backgroundColor: "#f8f9fa" }}>
                      <th
                        style={{
                          fontSize: "14px",
                          color: "#6c757d",
                          fontWeight: "normal",
                        }}
                      >
                        Category
                      </th>
                      <th
                        style={{
                          fontSize: "14px",
                          color: "#6c757d",
                          fontWeight: "normal",
                          textAlign: "right",
                        }}
                      >
                        Listings
                      </th>
                      <th
                        style={{
                          fontSize: "14px",
                          color: "#6c757d",
                          fontWeight: "normal",
                          textAlign: "right",
                        }}
                      >
                        Orders
                      </th>
                      <th
                        style={{
                          fontSize: "14px",
                          color: "#6c757d",
                          fontWeight: "normal",
                          textAlign: "right",
                        }}
                      >
                        Revenue
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {topCategories.map((category, index) => (
                      <tr
                        key={index}
                        className="bg-white shadow-sm rounded-lg mb-2"
                        style={{ border: "1px solid #e9ecef" }}
                      >
                        <td
                          style={{
                            fontSize: "14px",
                            color: "#212529",
                            padding: "12px",
                          }}
                        >
                          {category.category || "N/A"}
                        </td>
                        <td
                          style={{
                            fontSize: "14px",
                            color: "#212529",
                            padding: "12px",
                            textAlign: "right",
                          }}
                        >
                          {category.listings || 0}
                        </td>
                        <td
                          style={{
                            fontSize: "14px",
                            color: "#212529",
                            padding: "12px",
                            textAlign: "right",
                          }}
                        >
                          {(category.orders || 0).toLocaleString()}
                        </td>
                        <td
                          style={{
                            fontSize: "14px",
                            color: "#212529",
                            padding: "12px",
                            textAlign: "right",
                          }}
                        >
                          ETB {(category.revenue || 0).toLocaleString()}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <div className="col">
          <div className="card">
            <div className="card-header">
              <h5 className="card-title">Product Performance</h5>
              <p className="card-text text-muted">
                Top products by sales percentage
              </p>
            </div>
            <div className="card-body">
              {productPerformance.map((product, index) => (
                <div
                  key={index}
                  className="d-flex justify-content-between align-items-center mb-3"
                >
                  <div>
                    <div className="fw-bold">{product.product || "N/A"}</div>
                    <div className="text-muted small">
                      {product.orders || 0} orders
                    </div>
                  </div>
                  <div className="text-end">
                    <div className="text-success fw-bold">
                      {Number(product.salesPercentage || 0).toFixed(1)}%
                    </div>
                    <div className="text-muted small">of total sales</div>
                  </div>
                </div>
              ))}
              {(!productPerformance || productPerformance.length === 0) && (
                <p className="text-muted">
                  No product performance data available for the selected date
                  range.
                </p>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ProductReport;
